
name: ACA Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Ensure RG imported to state if exists
        working-directory: terraform
        run: |
          if az group show -n aca-rg &> /dev/null; then
            if ! terraform state list | grep -q '^azurerm_resource_group.rg$'; then
              terraform import azurerm_resource_group.rg /subscriptions/$(az account show --query id -o tsv)/resourceGroups/aca-rg
            fi
          fi

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Get Terraform Outputs
        working-directory: terraform
        run: |
          echo "ACR_SERVER=$(terraform output -raw acr_login_server)" >> $GITHUB_ENV
          echo "APP_NAME=$(terraform output -raw container_app_name)" >> $GITHUB_ENV
          echo "RG_NAME=$(terraform output -raw container_app_rg)" >> $GITHUB_ENV

      - name: Login to ACR
        run: |
          ACR_SERVER="${ACR_SERVER:-$(terraform -chdir=terraform output -raw acr_login_server)}"
          ACR_NAME="${ACR_SERVER%%.*}"
          az acr login --name "$ACR_NAME"

      - name: Build and Push Docker Image
        run: |
          ACR_SERVER=$(terraform -chdir=terraform output -raw acr_login_server)
          IMAGE="${ACR_SERVER}/myapp:latest"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Update Container App image
        run: |
          APP_NAME=$(terraform -chdir=terraform output -raw container_app_name)
          RG_NAME=$(terraform -chdir=terraform output -raw container_app_rg)
          ACR_SERVER=$(terraform -chdir=terraform output -raw acr_login_server)
          az containerapp update --name "$APP_NAME" --resource-group "$RG_NAME" --image "${ACR_SERVER}/myapp:latest"