name: ACA Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.6.0"

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Check if RG exists in Azure
        id: rg-check
        run: |
          if az group show -n aca-rg &> /dev/null; then
            echo "RG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "RG_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Import existing RG if needed
        if: env.RG_EXISTS == 'true'
        working-directory: terraform
        run: |
          # Terraform state にない場合だけ import
          if ! terraform state list | grep -q azurerm_resource_group.rg; then
            terraform import azurerm_resource_group.rg /subscriptions/${ARM_SUBSCRIPTION_ID}/resourceGroups/aca-rg
          fi

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Azure Container Registry Login
        working-directory: terraform
        run: |
          ACR_NAME=$(terraform output -raw acr_login_server | cut -d '.' -f1)
          az acr login --name $ACR_NAME

      - name: Build and Push Docker Image
        working-directory: .
        run: |
          IMAGE_NAME=$(terraform output -raw acr_login_server)/myapp:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Update Container App
        working-directory: terraform
        run: |
          APP_NAME=$(terraform output -raw container_app_name)
          RG_NAME=$(terraform output -raw container_app_rg)
          az containerapp update \
            --name $APP_NAME \
            --resource-group $RG_NAME \
            --image $(terraform output -raw acr_login_server)/myapp:latest
